repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=102400]  # can upload <100 MB to github
      - id: check-executables-have-shebangs
      - id: check-json
        exclude: ^config/settings\.json$
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
        exclude: ^config/settings\.json$
      - id: trailing-whitespace
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.9
    hooks:
      - id: commitizen
        stages: [commit-msg]
