"$schema" = 'https://starship.rs/config-schema.json'

# disable newline to command output
add_newline = false

# custom format
format = """
$directory\
$git_branch\
$git_status\
$time
$character
"""

[character]
format = "[\\$](green bold) "

[directory]
truncation_length = 2
format = "[\\[$path\\]]($style) "
style = "purple"

[git_branch]
symbol = ''
format = '\([$symbol$branch(:$remote_branch)]($style)\) '
style = "red"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = ''
ahead = ''
behind = ''
diverged = ''
up_to_date = '✓'
untracked = ''
stashed = ''
modified = '⚡'
staged = ''
renamed = ''
deleted = ''

[package]
disabled = true

[nodejs]
disabled = true

[gcloud]
disabled = true

[aws]
disabled = true

[time]
disabled = false
format = "[$time]($style)"
style = "green"

