# Theme
theme = "April Dark"
theme-dark = "Paper"

# Colors
foreground = "#1a1a1a"
background = "#fcfbf9"
palette-0 = "#1a1a1a"
palette-1 = "#a33a3a"
palette-2 = "#2b5a38"
palette-3 = "#a85a20"
palette-4 = "#4a7a8a"
palette-5 = "#4a3a6a"
palette-6 = "#3a7a6a"
palette-7 = "#c1beb5"
palette-8 = "#8c8a80"
palette-9 = "#c36a6a"
palette-10 = "#6b9a78"
palette-11 = "#c88a50"
palette-12 = "#7a9aaa"
palette-13 = "#8a7a9a"
palette-14 = "#6abaaa"

# Mouse & Input
omit-otty-prefix = true
cli-allow-overwrite = true

# Privileges
privilege-notification-on-finish = true

# confirm-close-tab = "always" (reset to default)

font-size = 18

# text-blink = true (reset to default)

auto-theme-dark-mode = false
palette-15 = "#ebebe6"
